name: Update LeetCode Data Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Explicit string for version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run snapshot script
        run: python daily_snapshot.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
        run: |
          # Only proceed if there are changes
          git diff --quiet || {
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add data.json
            git commit -m "Automated update: LeetCode stats $(date +'%Y-%m-%d')"
            git push origin HEAD:${{ github.ref_name }}
          }
