name: Update LeetCode Data Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permission

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run snapshot script
        run: python daily_snapshot.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check for changes first
          if git diff --quiet --exit-code; then
            echo "No changes detected"
            exit 0
          fi
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Automated update: LeetCode stats $(date +'%Y-%m-%d')"
          
          # Retry logic for push
          max_retries=3
          count=0
          until git push origin HEAD:${{ github.ref_name }}; do
            count=$((count+1))
            if [ $count -ge $max_retries ]; then
              echo "Push failed after $max_retries attempts"
              exit 1
            fi
            echo "Push failed, retrying in 3 seconds..."
            sleep 3
          done
